---
title: "index.Rmd"
output: html_document
---
# (Sophia's part, but if she needs help, all of us can pitch in!)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

index.Rmd File rubric:

In the Markdown document you create, you should leverage the functions written in the other files to create your report:

Write an introductory paragraph explaining the domain/data set (feel free to borrow from the brainstorm part of the assignment)
Write a summary paragraph that includes information calculated by your summary information function
Render your table and describe pertinent observations found in it
Describe the purpose of each chart (e.g., "this chart was intended to show the relationship between..."), render each chart, and describe pertinent observations found in each chart
In order to render this information, you'll need to read in your data in (only) your index.Rmd file, and pass your data to the functions provided in each script. If it isn't clear how to these pieces fit together, reach out to your TA.